#!/usr/bin/env node
/**
 * Translation coverage reporter for the content corpus.
 *
 * Scans every canonical English page under `src/content/` and checks which
 * locale translations exist at `src/content/<locale>/<same-relative-path>`.
 * Writes a human-readable matrix to `docs/translation-status.md` and prints a
 * summary. This is the single source of truth for "which pages still need
 * translating" — regenerate it instead of hand-maintaining a list.
 *
 * Usage:
 *   node scripts/translation-status.mjs           # regenerate the doc
 *   node scripts/translation-status.mjs --check    # exit 1 if any gaps (CI)
 *
 * Note: nav/marketing pages (home, pricing, faq, terms, privacy, money-back,
 * learn hub) are translated via `messages/<locale>.json`, not per-file. Each
 * `messages/<locale>.json` is a complete translation, so those pages are not
 * tracked here — this report covers the `src/content/` Markdown pages only.
 */
import fs from "fs";
import path from "path";
import matter from "gray-matter";

const ROOT = process.cwd();
const CONTENT_DIR = path.join(ROOT, "src", "content");
const OUT_FILE = path.join(ROOT, "docs", "translation-status.md");

// Mirror of SUPPORTED_LOCALES from src/lib/constants.ts (en excluded — it is
// the canonical source; all other entries are locale-prefixed translation
// dirs). Keep in sync with constants.ts, validate-content.mjs, and
// generate-content-derivatives.mjs.
const TRANSLATION_LOCALES = [
  "zh", "zh-TW", "ja", "ko", "es", "fr", "de", "pt", "ar", "hi", "ru", "th",
];
const LOCALE_DIR_SET = new Set(TRANSLATION_LOCALES);

/** Recursively collect *.md files under `dir`, returning paths relative to it. */
function walk(dir, base = dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(abs, base, acc);
    else if (entry.isFile() && entry.name.endsWith(".md")) acc.push(path.relative(base, abs));
  }
  return acc;
}

/** Canonical English pages: top-level *.md not inside a locale dir, excluding `_`-prefixed. */
function canonicalPages() {
  return walk(CONTENT_DIR)
    .filter((rel) => {
      const first = rel.split(path.sep)[0];
      if (LOCALE_DIR_SET.has(first)) return false; // a translation file
      if (path.basename(rel).startsWith("_")) return false; // _template.md
      return true;
    })
    .sort();
}

function slugFor(rel) {
  const noExt = rel.replace(/\.md$/, "").split(path.sep).join("/");
  return "/" + noExt;
}

function titleFor(absPath, fallback) {
  try {
    const fm = matter(fs.readFileSync(absPath, "utf8")).data;
    if (fm && typeof fm.title === "string") return fm.title;
  } catch {}
  return fallback;
}

const pages = canonicalPages();

const rows = pages.map((rel) => {
  const abs = path.join(CONTENT_DIR, rel);
  const present = {};
  for (const loc of TRANSLATION_LOCALES) {
    present[loc] = fs.existsSync(path.join(CONTENT_DIR, loc, rel));
  }
  const have = TRANSLATION_LOCALES.filter((l) => present[l]).length;
  return { rel, slug: slugFor(rel), title: titleFor(abs, slugFor(rel)), present, have };
});

// Per-locale totals
const localeTotals = {};
for (const loc of TRANSLATION_LOCALES) {
  localeTotals[loc] = rows.filter((r) => r.present[loc]).length;
}
const total = rows.length;
const fully = rows.filter((r) => r.have === TRANSLATION_LOCALES.length).length;
const untranslated = rows.filter((r) => r.have === 0).length;

// ── Build markdown ──────────────────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10);
const yes = "✅";
const no = "❌";

let md = `# Translation Status

> Generated by \`scripts/translation-status.mjs\`. Do not edit by hand —
> run \`node scripts/translation-status.mjs\` to regenerate.
>
> Last generated: ${today}

Tracks per-page translation coverage for the ${total} canonical English pages
under \`src/content/\`. A page is "fully translated" when a file exists at
\`src/content/<locale>/<same-path>\` for all ${TRANSLATION_LOCALES.length}
translation locales.

Nav/marketing pages (home, pricing, FAQ, terms, privacy, money-back, learn hub)
are translated via \`messages/<locale>.json\` and are complete across all
locales; they are not tracked here.

## Summary

- **Canonical pages:** ${total}
- **Fully translated (all ${TRANSLATION_LOCALES.length} locales):** ${fully}
- **Partially translated:** ${total - fully - untranslated}
- **English-only (0 translations):** ${untranslated}

### Coverage by locale

| Locale | Translated | Coverage |
|---|---|---|
${TRANSLATION_LOCALES.map((l) => `| ${l} | ${localeTotals[l]} / ${total} | ${((localeTotals[l] / total) * 100).toFixed(0)}% |`).join("\n")}

## Coverage matrix

| Page | ${TRANSLATION_LOCALES.join(" | ")} | Have |
|---|${TRANSLATION_LOCALES.map(() => "---").join("|")}|---|
${rows
  .map(
    (r) =>
      `| \`${r.slug}\` | ${TRANSLATION_LOCALES.map((l) => (r.present[l] ? yes : no)).join(" | ")} | ${r.have}/${TRANSLATION_LOCALES.length} |`,
  )
  .join("\n")}

## Pages needing translation

`;

const gaps = rows.filter((r) => r.have < TRANSLATION_LOCALES.length);
if (gaps.length === 0) {
  md += "All pages are fully translated. 🎉\n";
} else {
  for (const r of gaps) {
    const missing = TRANSLATION_LOCALES.filter((l) => !r.present[l]);
    md += `- \`${r.slug}\` — missing: ${missing.join(", ")}\n`;
  }
}

md += "\n";

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, md);

console.log(`Translation status written to ${path.relative(ROOT, OUT_FILE)}`);
console.log(`Pages: ${total} | Fully translated: ${fully} | English-only: ${untranslated}`);
for (const loc of TRANSLATION_LOCALES) {
  console.log(`  ${loc.padEnd(6)} ${localeTotals[loc]}/${total}`);
}

if (process.argv.includes("--check") && gaps.length > 0) {
  console.error(`\n${gaps.length} page(s) are not fully translated.`);
  process.exit(1);
}
